---
- hosts: cloud
  tasks:
    - name: install git
      apt: pkg=git state=installed update_cache=true

    - name: install apache 2
      apt: pkg=apache2 state=latest update_cache=true

    - name: install the dependencies
      command: apt-get --no-install-recommends -y install \build-essential pkg-config erlang \libicu-dev libmozjs185-dev libcurl4-openssl-dev

    - name: create partition for volume
      filesystem: fstype=ext4 dev=/dev/vdb

    - name: create couchdb directory
      file: path=/mnt/couchdb state=directory

    - name: mount the volums
      mount: name=/mnt/couchdb src=/dev/vdb fstype=ext4 state=mounted 

    - name: add auto mount when start
      lineinfile: dest: /etc/fstab
                  line: '/dev/vdb      /mnt/couchdb    ext4    defaults        2'
              
    - name: download couchdb
      get_url: url: "http://apache-mirror.rbc.ru/pub/apache/couchdb/source/2.0.0/apache-couchdb-2.0.0.tar.gz"
               dest: /home/ubuntu

    - name: tar file
      unarchive: src: apache-couchdb-2.0.0.tar.gz
                 dest: /home/ubuntu

    - name: enter the folder
      file: path=/home/ubuntu/apache-couchdb-2.0.0/ state=directory

    - name: setup couchdb
      shell: ./configure && make release

    - name: add user
      shell: sudo adduser --system \
             --no-create-home \
             --shell /bin/bash \
             --group --gecos \
             "CouchDB Administrator" couchdb

    - name: copy file
      shell: cp -R rel/couchdb /home/couchdb

    - name: Change the ownership of the CouchDB directories
      shell: chown -R couchdb:couchdb /home/couchdb

    - name: install systemd libpam-systemd systemd-ui
      shell: apt-get -y install systemd libpam-systemd systemd-ui

    - name: create service file
      lineinfile: dest: /etc/systemd/system/couchdb.service
                  line: '[Unit]
                        Description=Couchdb service
                        After=network.target
 
                        [Service]
                        Type=simple
                        User=couchdb
                        ExecStart=/home/couchdb/bin/couchdb -o /dev/stdout -e /dev/stderr
                        Restart=always

                        [Install]
                        WantedBy=multi-user.target'

    - name: add service
      shell: systemctl  daemon-reload

    - name: add service
      shell: systemctl  start couchdb.service

    - name: add service
      shell: systemctl  enable couchdb.service

    - name: install curl
      apt: pkg=curl state=latest

    - name: change bind_address
      lineinfile: dest=/etc/couchdb/local.ini
              regexp='^;bind_address'
              insertafter=";port"
              line="bind_address = 0.0.0.0"

    